# Generated by Django 4.0.4 on 2022-05-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=10)),
                ('genero', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('monto', models.FloatField()),
            ],
        ),
    ]
