# Generated by Django 4.0.4 on 2022-05-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoniApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido_prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=10)),
                ('genero', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('monto', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Formulario',
        ),
    ]
