# Generated by Django 4.0.4 on 2022-05-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoniApp', '0006_alter_pedido_prestamo_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='moniapp')),
            ],
        ),
    ]
